---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-apps
spec:
  interval: 1m0s
  path: ./kustomize
  prune: true
  targetNamespace: flux-apps
  serviceAccountName: dev-team
  sourceRef:
    kind: GitRepository
    name: podinfo
