---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: openshift
  url: https://github.com/sabre1041/flux-podinfo
